language: r
cache: packages

os: 
  - osx
  - linux

before_install:
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmagick++-dev; fi

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'library(goodpractice); gp()'
