language: r
cache: packages

warnings_are_errors: false

os: 
  # disabled osx, because of openmp dependency
  # - osx
  - linux

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmagick++-dev; fi
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  
script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz

after_success:
  - travis_wait 60 Rscript -e 'lintr::lint_package()'
  - travis_wait 60 Rscript -e 'library(covr); codecov()'
  - travis_wait 60 Rscript -e 'library(goodpractice); gp()'
