#' calculate the overall fit of the particle to the data
#' @param sum_stats summary statistics of the tree generated by the particle
#' @param emp_stats summary statistics of the empirical tree
#' @return sum of normalized differences between the summary statistics
#' @export
calc_fit <- function(sum_stats,
                     emp_stats) {

  diff <- (sum_stats[1:8]  - emp_stats[1:8])
  nltt_diff <- diff[1] # store nltt_diff, this one can not be normalized
  diff <- diff * diff
  diff <- diff / abs(emp_stats[1:8])
  diff[1] <- nltt_diff
  return(sum(diff))
}
