#' calculate the overall fit of the particle to the data
#' @param sum_stats summary statistics of the tree generated by the particle
#' @param emp_stats summary statistics of the empirical tree
#' @return sum of normalized differences between the summary statistics
#' @export
calc_fit <- function(sum_stats,
                     emp_stats) {

  diff <- sum_stats[1:4]  - emp_stats[1:4]
  diff <- diff * diff
  diff <- diff / c(0.25, 2, 0.8, 75)
  return(sum(diff))
}
