# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' simulate a tree using environmental diversification
#' @param parameters a vector of the four paramaters of the model
#' @param waterlevel_changes a vector that indicates the time points of water level changes
#' @param seed pseudo-random number generator seed
#' @param crown_age crown age of the tree to be simulated
#' @param max_lin maximum number of lineages
#' @return newick string
#' @export
create_tree_cpp <- function(parameters, waterlevel_changes, seed, crown_age, max_lin) {
    .Call('_enviDiv_create_tree_cpp', PACKAGE = 'enviDiv', parameters, waterlevel_changes, seed, crown_age, max_lin)
<<<<<<< HEAD
=======
}

#' simulate a tree using environmental diversification
#' @param n size of vector
#' @param num_threads number of threads
#' @return vector of squared numbers
#' @export
sq_numbers_cpp_tbb <- function(n, num_threads) {
    .Call('_enviDiv_sq_numbers_cpp_tbb', PACKAGE = 'enviDiv', n, num_threads)
}

#' simulate a tree using environmental diversification
#' @param model a vector of the four paramaters of the model
#' @param num_repl a vector that indicates the time points of water level changes
#' @param crown_age crown age of the tree to be simulated
#' @param min_lin minimum number of lineages
#' @param max_lin maximum number of lineages
#' @param num_threads
#' @return newick string
#' @export
create_ref_table_cpp <- function(model, num_repl, crown_age, min_lin, max_lin, num_threads) {
    .Call('_enviDiv_create_ref_table_cpp', PACKAGE = 'enviDiv', model, num_repl, crown_age, min_lin, max_lin, num_threads)
>>>>>>> 7836f6b3d7b4005a326564439c0cf333fcfa50ce
}

