# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' test exponential generator
#' @param lambda input parameter
#' @return number drawn from exponential distribution
#' @export
generate_expon <- function(lambda) {
    .Call('_enviDiv_generate_expon', PACKAGE = 'enviDiv', lambda)
}

#' simulate a tree using environmental diversification
#' @param parameters a vector of the four paramaters of the model
#' @param waterlevel_changes a vector that indicates the time points of water level changes
#' @param seed pseudo-random number generator seed
#' @param crown_age crown age of the tree to be simulated
#' @return newick string
#' @export
create_tree_cpp <- function(parameters, waterlevel_changes, seed, crown_age) {
    .Call('_enviDiv_create_tree_cpp', PACKAGE = 'enviDiv', parameters, waterlevel_changes, seed, crown_age)
}

